{
 "title": "libreSpeed Dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "Speed Tests History",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 19, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Tests" } },
   "targets": [
    {
     "rawSql": "SELECT \r\n    UNIX_TIMESTAMP(DATE_FORMAT(timestamp, '%Y-%m-%d %H:%i:00')) AS time,\r\n    COUNT(*) AS 'Quantidade de Testes'\r\nFROM \r\n    speedtest_users\r\nGROUP BY \r\n    UNIX_TIMESTAMP(DATE_FORMAT(timestamp, '%Y-%m-%d %H:%i:00'))\r\nORDER BY \r\n    'timestamp' DESC;\r\n"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 19, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT id AS `Total Speed Probes` FROM speedtest_users\r\nORDER BY id DESC\r\nlimit 1;\r\n"
    }
   ]
  },
  {
   "title": "Avarage Download Rate (Mbps)",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "Mbits" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \r\n    AVG(CAST(dl AS DECIMAL(10, 2))) AS 'Velocidade Média de Download (Mbps)'\r\nFROM \r\n    speedtest_users\r\n"
    }
   ]
  },
  {
   "title": "Avarage Download Rate (Mbps)",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "Mbits" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \r\n    AVG(CAST(dl AS DECIMAL(10, 2))) AS 'Velocidade Média de Download (Mbps)'\r\nFROM \r\n    speedtest_users\r\n"
    }
   ]
  },
  {
   "title": "Avarage Jitter",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \r\n    AVG(CAST(jitter AS DECIMAL(10, 2))) AS 'Jitter'\r\nFROM \r\n    speedtest_users\r\n"
    }
   ]
  },
  {
   "title": "Avarage Latency",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \r\n    AVG(CAST(ping AS DECIMAL(10, 2))) AS 'ping'\r\nFROM \r\n    speedtest_users\r\n"
    }
   ]
  },
  {
   "title": "Avarage Jitter History",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT \r\n    UNIX_TIMESTAMP(DATE_FORMAT(timestamp, '%Y-%m-%d %H:%i:00')) AS time,\r\n    AVG(CAST(jitter AS DECIMAL(10, 2))) AS 'Jitter Médio (ms)'\r\nFROM \r\n    speedtest_users\r\nGROUP BY \r\n    UNIX_TIMESTAMP(DATE_FORMAT(timestamp, '%Y-%m-%d %H:%i:00'))\r\nORDER BY \r\n    'timestamp' DESC;\r\n"
    }
   ]
  },
  {
   "title": "Last 10 Probes",
   "type": "table",
   "gridPos": { "h": 10, "w": 16, "x": 0, "y": 14 },
   "targets": [
    {
     "rawSql": "SELECT \r\n    ip AS 'IP',\r\n    dl AS 'Downlink (Mbps)',\r\n    ul AS 'Uplink (Mbps)',\r\n    ping AS 'Latência (ms)',\r\n    jitter AS 'Jitter (ms)'\r\nFROM \r\n    speedtest_users\r\nORDER BY \r\n    timestamp DESC\r\nLIMIT 10;\r\n"
    }
   ]
  },
  {
   "title": "Avarage Ping History",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT \r\n    UNIX_TIMESTAMP(DATE_FORMAT(timestamp, '%Y-%m-%d %H:%i:00')) AS time,\r\n    AVG(CAST(ping AS DECIMAL(10, 2))) AS 'Ping Médio (ms)'\r\nFROM \r\n    speedtest_users\r\nGROUP BY \r\n    UNIX_TIMESTAMP(DATE_FORMAT(timestamp, '%Y-%m-%d %H:%i:00'))\r\nORDER BY \r\n    'timestamp' DESC;\r\n"
    }
   ]
  }
 ]
}